/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libShareAudio */

#ifndef _Included_libShareAudio
#define _Included_libShareAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libShareAudio
 * Method:    SA_Init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1Init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_Server
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1Server
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_Client
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1Client
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1Close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_SetVolumeModifier
 * Signature: (FJ)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1SetVolumeModifier
  (JNIEnv *, jclass, jfloat, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_GetVolumeModifier
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_libShareAudio_SA_1GetVolumeModifier
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_ListAllAudioDevices
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1ListAllAudioDevices
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_ListAllAudioDevicesStr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libShareAudio_SA_1ListAllAudioDevicesStr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1Free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_Version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libShareAudio_SA_1Version
  (JNIEnv *, jclass);

/*
 * Class:     libShareAudio
 * Method:    SA_Setup
 * Signature: (ILjava/lang/String;IIIFID)J
 */
JNIEXPORT jlong JNICALL Java_libShareAudio_SA_1Setup
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint, jfloat, jint, jdouble);

/*
 * Class:     libShareAudio
 * Method:    SA_GetStats
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libShareAudio_SA_1GetStats
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_SetLogNULL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1SetLogNULL
  (JNIEnv *, jclass);

/*
 * Class:     libShareAudio
 * Method:    SA_SetLogFILE
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1SetLogFILE
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     libShareAudio
 * Method:    SA_SetLogCONSOLE
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1SetLogCONSOLE
  (JNIEnv *, jclass, jint);

/*
 * Class:     libShareAudio
 * Method:    SA_TestDLL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_libShareAudio_SA_1TestDLL
  (JNIEnv *, jclass);

/*
 * Class:     libShareAudio
 * Method:    SA_ReadLastMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libShareAudio_SA_1ReadLastMsg
  (JNIEnv *, jclass);

/*
 * Class:     libShareAudio
 * Method:    SA_SendMsg
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_libShareAudio_SA_1SendMsg
  (JNIEnv *, jclass, jstring);

/*
 * Class:     libShareAudio
 * Method:    SA_InitWavRecord
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1InitWavRecord
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     libShareAudio
 * Method:    SA_CloseWavRecord
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1CloseWavRecord
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_GetWavFilePtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_libShareAudio_SA_1GetWavFilePtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libShareAudio
 * Method:    SA_SetKey
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1SetKey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     libShareAudio
 * Method:    SA_SetMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_libShareAudio_SA_1SetMode
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
